apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-go
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-world-go
  template:
    metadata:
      labels:
        app: hello-world-go
    spec:
      containers:
      - name: helloworld-go-app
        image: nunosantos251/helloworld-go-app:1.0
        ports:
        - containerPort: 8080