apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-go
  template:
    metadata:
      labels:
        app: hello-world-go
    spec:
      containers:
      - name: helloworld-go-app
        image: nunosantos251/helloworld-go-app:1.2
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "200Mi"
            cpu: "200m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080